site :opscode
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'mackerel-agent',
  :git => 'https://github.com/mackerelio/cookbook-mackerel-agent.git'
cookbook 'zabbix', :git => 'https://github.com/tamu222i/zabbix-cookbook.git'
